[NOLD-16] Added Twisted client and Websocket transport
neurobat/barrister pull request #4
Opened 2017-02-13 16:51 UTC by cgrigis

2017-02-20 09:11 UTC, pierluca requested changes
LGTM but I wouldn't merge this into neurobat:master , if anything because we have a pending pull request with the Barrister guy from our master.

2017-02-20 09:11 UTC, pierluca commented on barrister/runtime.py
> +from twisted.internet import defer
adding this here, one needs to add this to the dependencies (setup.py / requirements.txt)

2017-02-20 09:11 UTC, pierluca commented on barrister/runtime.py
> +        print("RPC --> {!r}".format(req))
shouldn't we use the logging module instead?

2017-02-20 09:11 UTC, pierluca commented on barrister/runtime.py
> +        print("<-- RPC {!r}".format(message))
logging ?

2017-02-20 09:11 UTC, pierluca commented on barrister/runtime.py
> +    def get_iface(self):
it makes sense that internally this is called iface, but from a "user" perspective, shouldn't this really be the `get_api`?

2017-02-21 10:53 UTC, cgrigis commented on barrister/runtime.py
> +from twisted.internet import defer
- [ ] Add Twisted as a dependency in `requirements.txt` and `setup.py`

2017-02-21 10:54 UTC, cgrigis commented on barrister/runtime.py
> +        print("RPC --> {!r}".format(req))
- [ ] Use logging module instead of `print` statements

2017-02-21 10:55 UTC, cgrigis commented on barrister/runtime.py
> +    def get_iface(self):
- [ ] Rename `get_iface()` to `get_api()`

2017-02-21 15:36 UTC, closed without merging